// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

export interface IndoorBillboardPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  sections?: unknown;
  metadata?: unknown;
  order?: number;
  icon?: string;
  thumbnail?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  cta_text?: string;
  cta_link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface LocationPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  sections?: unknown;
  metadata?: unknown;
  location: string;
  cta_text?: string;
  cta_link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  sections?: unknown;
  metadata?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Solution {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  sections?: unknown;
  metadata?: unknown;
  category?: "foundational" | "lead-gen" | "branding-awareness";
  order?: number;
  icon?: string;
  thumbnail?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  cta_text?: string;
  cta_link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    indoor_billboards: IndoorBillboardPage;
    locations: LocationPage;
    pages: Page;
    solutions: Solution;
  }
}